name: speech_buttons
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/sample1RO.mp3
    - assets/audio/sample1FR.mp3
    - assets/audio/sample2RO.mp3
    - assets/audio/sample2FR.mp3
    - assets/audio/sample3RO.mp3
    - assets/audio/sample3FR.mp3
    - assets/audio/sample4RO.mp3
    - assets/audio/sample4FR.mp3
