name: Check the quality of my code
on:
  push:

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run format
        run: flutter format -l 120 --set-exit-if-changed .
      - name: Run analysis currency convertor
        working-directory: ./currency_convertor
        run: flutter analyze
      - name: Run analysis guess my number
        working-directory: ./guess_my_number
        run: flutter analyze
      - name: Run analysis number shape
        working-directory: ./number_shape
        run: flutter analyze
      - name: Run analysis speech buttons
        working-directory: ./speech_buttons
        run: flutter analyze
      - name: Run analysis tic-tac-toe
        working-directory: ./tic_tac_toe
        run: flutter analyze
      - name: Run analysis movies-list
        working-directory: ./movies_list
        run: flutter analyze